In [1]:
import numpy as np

In [3]:
#!pip install numpy

In [4]:
my_list = [10,20,30,40,50]

In [5]:
type(my_list)

list

In [6]:
np.array(my_list)

array([10, 20, 30, 40, 50])

In [7]:
my_array = np.array(my_list)

In [8]:
type(my_array)

numpy.ndarray

In [10]:
my_array.max()

50

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.random.random(5)

array([0.58349038, 0.30727893, 0.91474003, 0.12239553, 0.73347271])

In [14]:
# array arithmetic

In [15]:
my_list1 = [1,2]

In [16]:
my_list2 = [2,3]

In [17]:
my_list1 + my_list2

[1, 2, 2, 3]

In [18]:
my_array_list1 = np.array(my_list1)

In [19]:
my_array_list2 = np.array(my_list2)

In [20]:
my_array_list1 + my_array_list2

array([3, 5])

In [21]:
my_array_list1 * my_array_list2

array([2, 6])

In [22]:
my_array_list1 -my_array_list2

array([-1, -1])

In [24]:
my_list1 * 5

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [25]:
my_array_list1 * 5

array([ 5, 10])

In [27]:
# arange & indexing

In [30]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np_array = np.arange(0,10)

In [35]:
np_array[0]

0

In [36]:
np_array[-1]

9

In [37]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [38]:
np_array[2:6:2]

array([2, 4])

In [39]:
#random

In [41]:
np.random.randn(4)

array([ 1.62701879, -1.25962795, -0.22056658,  0.13677768])

In [42]:
np.random.randn(4,4)

array([[ 0.12398591, -0.70104013,  0.37977871, -0.67567931],
       [-0.40859837, -0.34690684, -0.76666322, -0.85903462],
       [-0.43171348,  0.627964  ,  0.38652421,  1.76400569],
       [ 2.69268009,  2.04514366,  0.97649075,  0.55528535]])

In [43]:
np.random.randint(1,300,5)

array([ 39,  90, 186, 173, 243])