In [8]:
import numpy as np

In [9]:
my_matrix = [[5,10], [15,20]]

In [10]:
my_matrix[0]

[5, 10]

In [11]:
my_matrix[0][1]

10

In [12]:
# row + column

In [15]:
numpy_matrix = np.array([[5,10],[15,20]])

In [16]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [17]:
numpy_matrix[1][0]

15

In [18]:
numpy_matrix.sum()

50

In [20]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.random.random((3,2))

array([[0.07796081, 0.66291203],
       [0.1298259 , 0.0478327 ],
       [0.44603403, 0.69341559]])

In [25]:
#matrix arithmetic

In [26]:
first_array = np.array([[10,20],[30,40]])

In [27]:
second_array = np.array([[5,15],[25,35]])

In [28]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [29]:
third_array = np.array([50,60])

In [30]:
first_array + third_array

array([[ 60,  80],
       [ 80, 100]])

In [33]:
third_array = np.array([[10],[20]])

In [34]:
third_array

array([[10],
       [20]])

In [36]:
third_array.shape

(2, 1)

In [39]:
first_array.shape

(2, 2)

In [40]:
first_array + third_array

array([[20, 30],
       [50, 60]])

In [41]:
# matrix multiplication

In [42]:
first_array

array([[10, 20],
       [30, 40]])

In [43]:
second_array

array([[ 5, 15],
       [25, 35]])

In [44]:
first_array * second_array

array([[  50,  300],
       [ 750, 1400]])

In [45]:
# dot product

In [49]:
first_matrix = np.array([[10,20,30]])

In [50]:
first_matrix

array([[10, 20, 30]])

In [51]:
first_matrix.shape

(1, 3)

In [52]:
second_matrix = np.array([[2,3],[2,3],[2,3]])

In [53]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [54]:
second_matrix.shape

(3, 2)

In [56]:
#first matrix * second matrix --> hata verir.

In [58]:
result_matrix = first_matrix.dot(second_matrix)

In [59]:
result_matrix

array([[120, 180]])

In [60]:
result_matrix.shape

(1, 2)