In [1]:
import numpy as np

In [2]:
new_array = np.random.randint(1,100,20)

In [3]:
new_array

array([81,  3, 37, 63, 21, 23, 15, 48, 92, 20, 78, 49, 73, 80, 49, 40, 27,
       93, 66, 88])

In [4]:
new_array > 25

array([ True, False,  True,  True, False, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [6]:
new_array[new_array > 25]

array([81, 37, 63, 48, 92, 78, 49, 73, 80, 49, 40, 27, 93, 66, 88])

In [7]:
new_array[new_array < 25]

array([ 3, 21, 23, 15, 20])

In [8]:
# transpose & reshape

In [11]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [12]:
matrix_array.shape

(3, 2)

In [13]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [14]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [16]:
random_array = np.random.random((6,1))

In [17]:
random_array

array([[0.1514199 ],
       [0.22814061],
       [0.58679519],
       [0.9946619 ],
       [0.0082883 ],
       [0.38607851]])

In [18]:
random_array.shape

(6, 1)

In [20]:
random_array.reshape(2,3)

array([[0.1514199 , 0.22814061, 0.58679519],
       [0.9946619 , 0.0082883 , 0.38607851]])

In [21]:
random_array.reshape(3,2)

array([[0.1514199 , 0.22814061],
       [0.58679519, 0.9946619 ],
       [0.0082883 , 0.38607851]])

In [23]:
# z-score

In [24]:
data = np.array([10,12,13,15,18,25,100,105])

In [25]:
# outlier

In [26]:
mean = np.mean(data)

In [27]:
mean

37.25

In [29]:
data.sum() / len(data)

37.25

In [30]:
std = np.std(data)

In [31]:
std

37.9333296719389

In [34]:
z_score = (data - mean) / std

In [35]:
z_score

array([-0.71836562, -0.66564154, -0.6392795 , -0.58655542, -0.50746929,
       -0.322935  ,  1.65421809,  1.78602829])

In [36]:
data[z_score > 1]

array([100, 105])

In [38]:
# math equations

In [39]:
# 2x + 3y = 8 and 5x + 7y = 19

In [45]:
#coefficient

In [50]:
A = np.array([[2,3],[5,7]])

In [51]:
A

array([[2, 3],
       [5, 7]])

In [52]:
#constant

In [53]:
b = np.array([8,19])

In [54]:
b

array([ 8, 19])

In [56]:
solution = np.linalg.solve(A,b)

In [57]:
solution

array([1., 2.])